# Generated by Django 5.2.12 on 2026-03-24 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("identity_document", "identity_document"),
                            ("employment_contract", "employment_contract"),
                            ("payslip", "payslip"),
                            ("invoice", "invoice"),
                            ("tax_form", "tax_form"),
                            ("other", "other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("extracted_fields", models.JSONField(default=dict)),
                ("raw_text", models.TextField(blank=True)),
                ("model_used", models.CharField(max_length=100)),
                ("processing_time_ms", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
